/**
 * FIT file type enum
 * Defines the type of data contained in the FIT file
 */
export enum FitFileType {
    DEVICE = 1,
    SETTINGS = 2,
    SPORT = 3,
    ACTIVITY = 4,
    WORKOUT = 5,
    COURSE = 6,
    SCHEDULES = 7,
    WEIGHT = 9,
    TOTALS = 10,
    GOALS = 11,
    BLOOD_PRESSURE = 14,
    MONITORING_A = 15,
    ACTIVITY_SUMMARY = 20,
    MONITORING_DAILY = 28,
    MONITORING_B = 32,
    SEGMENT = 34,
    SEGMENT_LIST = 35,
    EXD_CONFIGURATION = 40,
    MFG_RANGE_MIN = 0xF7,
    MFG_RANGE_MAX = 0xFE,
}

/**
 * FIT manufacturer enum
 * Represents equipment manufacturers
 */
export enum FitManufacturer {
    GARMIN = 1,
    GARMIN_FR405_ANTFS = 2, // Do not use. Used by FR405 for ANTFS man id.
    ZEPHYR = 3,
    DAYTON = 4,
    IDT = 5,
    SRM = 6,
    QUARQ = 7,
    IBIKE = 8,
    SARIS = 9,
    SPARK_HK = 10,
    TANITA = 11,
    ECHOWELL = 12,
    DYNASTREAM_OEM = 13,
    NAUTILUS = 14,
    DYNASTREAM = 15,
    TIMEX = 16,
    METRIGEAR = 17,
    XELIC = 18,
    BEURER = 19,
    CARDIOSPORT = 20,
    A_AND_D = 21,
    HMM = 22,
    SUUNTO = 23,
    THITA_ELEKTRONIK = 24,
    GPULSE = 25,
    CLEAN_MOBILE = 26,
    PEDAL_BRAIN = 27,
    PEAKSWARE = 28,
    SAXONAR = 29,
    LEMOND_FITNESS = 30,
    DEXCOM = 31,
    WAHOO_FITNESS = 32,
    OCTANE_FITNESS = 33,
    ARCHINOETICS = 34,
    THE_HURT_BOX = 35,
    CITIZEN_SYSTEMS = 36,
    MAGELLAN = 37,
    OSYNCE = 38,
    HOLUX = 39,
    CONCEPT2 = 40,
    SHIMANO = 41,
    ONE_GIANT_LEAP = 42,
    ACE_SENSOR = 43,
    BRIM_BROTHERS = 44,
    XPLOVA = 45,
    PERCEPTION_DIGITAL = 46,
    BF1SYSTEMS = 47,
    PIONEER = 48,
    SPANTEC = 49,
    METALOGICS = 50,
    FOUR_IIIIS = 51,
    SEIKO_EPSON = 52,
    SEIKO_EPSON_OEM = 53,
    IFOR_POWELL = 54,
    MAXWELL_GUIDER = 55,
    STAR_TRAC = 56,
    BREAKAWAY = 57,
    ALATECH_TECHNOLOGY_LTD = 58,
    MIO_TECHNOLOGY_EUROPE = 59,
    ROTOR = 60,
    GEONAUTE = 61,
    ID_BIKE = 62,
    SPECIALIZED = 63,
    WTEK = 64,
    PHYSICAL_ENTERPRISES = 65,
    NORTH_POLE_ENGINEERING = 66,
    BKOOL = 67,
    CATEYE = 68,
    STAGES_CYCLING = 69,
    SIGMASPORT = 70,
    TOMTOM = 71,
    PERIPEDAL = 72,
    WATTBIKE = 73,
    MOXY = 76,
    CICLOSPORT = 77,
    POWERBAHN = 78,
    ACORN_PROJECTS_APS = 79,
    LIFEBEAM = 80,
    BONTRAGER = 81,
    WELLGO = 82,
    SCOSCHE = 83,
    MAGURA = 84,
    WOODWAY = 85,
    ELITE = 86,
    NIELSEN_KELLERMAN = 87,
    DK_CITY = 88,
    TACX = 89,
    DIRECTION_TECHNOLOGY = 90,
    MAGTONIC = 91,
    ONE_PART_CARBON = 92,
    INSIDE_RIDE_TECHNOLOGIES = 93,
    SOUND_OF_MOTION = 94,
    STRYD = 95,
    ICG = 96, // Indoorcycling Group
    MI_PULSE = 97,
    BSX_ATHLETICS = 98,
    LOOK = 99,
    CAMPAGNOLO_SRL = 100,
    BODY_BIKE_SMART = 101,
    PRAXISWORKS = 102,
    LIMITS_TECHNOLOGY = 103, // Limits Technology Ltd.
    TOPACTION_TECHNOLOGY = 104, // TopAction Technology Inc.
    COSINUSS = 105,
    FITCARE = 106,
    MAGENE = 107,
    GIANT_MANUFACTURING_CO = 108,
    TIGRASPORT = 109,
    SALUTRON = 110,
    TECHNOGYM = 111,
    BRYTON_SENSORS = 112,
    LATITUDE_LIMITED = 113,
    SOARING_TECHNOLOGY = 114,
    IGPSPORT = 115,
    THINKRIDER = 116,
    GOPHER_SPORT = 117,
    WATERROWER = 118,
    ORANGETHEORY = 119,
    INPEAK = 120,
    KINETIC = 121,
    JOHNSON_HEALTH_TECH = 122,
    POLAR_ELECTRO = 123,
    SEESENSE = 124,
    NCI_TECHNOLOGY = 125,
    IQSQUARE = 126,
    LEOMO = 127,
    IFIT_COM = 128,
    COROS_BYTE = 129,
    VERSA_DESIGN = 130,
    CHILEAF = 131,
    CYCPLUS = 132,
    GRAVAA_BYTE = 133,
    SIGEYI = 134,
    COOSPO = 135,
    GEOID = 136,
    BOSCH = 137,
    KYTO = 138,
    KINETIC_SPORTS = 139,
    DECATHLON_BYTE = 140,
    TQ_SYSTEMS = 141,
    TAG_HEUER = 142,
    KEISER_FITNESS = 143,
    ZWIFT_BYTE = 144,
    PORSCHE_EP = 145,
    BLACKBIRD = 146,
    MEILAN_BYTE = 147,
    EZON = 148,
    LAISI = 149,
    MYZONE = 150,
    ABAWO = 151,
    BAFANG = 152,
    LUHONG_TECHNOLOGY = 153,
    DEVELOPMENT = 255,
    HEALTHANDLIFE = 257,
    LEZYNE = 258,
    SCRIBE_LABS = 259,
    ZWIFT = 260,
    WATTEAM = 261,
    RECON = 262,
    FAVERO_ELECTRONICS = 263,
    DYNOVELO = 264,
    STRAVA = 265,
    PRECOR = 266, // Amer Sports
    BRYTON = 267,
    SRAM = 268,
    NAVMAN = 269, // MiTAC Global Corporation (Mio Technology)
    COBI = 270, // COBI GmbH
    SPIVI = 271,
    MIO_MAGELLAN = 272,
    EVESPORTS = 273,
    SENSITIVUS_GAUGE = 274,
    PODOON = 275,
    LIFE_TIME_FITNESS = 276,
    FALCO_E_MOTORS = 277, // Falco eMotors Inc.
    MINOURA = 278,
    CYCLIQ = 279,
    LUXOTTICA = 280,
    TRAINER_ROAD = 281,
    THE_SUFFERFEST = 282,
    FULLSPEEDAHEAD = 283,
    VIRTUALTRAINING = 284,
    FEEDBACKSPORTS = 285,
    OMATA = 286,
    VDO = 287,
    MAGNETICDAYS = 288,
    HAMMERHEAD = 289,
    KINETIC_BY_KURT = 290,
    SHAPELOG = 291,
    DABUZIDUO = 292,
    JETBLACK = 293,
    COROS = 294,
    VIRTUGO = 295,
    VELOSENSE = 296,
    CYCLIGENTINC = 297,
    TRAILFORKS = 298,
    MAHLE_EBIKEMOTION = 299,
    NURVV = 300,
    MICROPROGRAM = 301,
    ZONE5CLOUD = 302,
    GREENTEG = 303,
    YAMAHA_MOTORS = 304,
    WHOOP = 305,
    GRAVAA = 306,
    ONELAP = 307,
    MONARK_EXERCISE = 308,
    FORM = 309,
    DECATHLON = 310,
    SYNCROS = 311,
    HEATUP = 312,
    CANNONDALE = 313,
    TRUE_FITNESS = 314,
    RGT_CYCLING = 315,
    VASA = 316,
    RACE_REPUBLIC = 317,
    FAZUA = 318,
    OREKA_TRAINING = 319,
    LSEC = 320, // Lishun Electric & Communication
    LULULEMON_STUDIO = 321,
    SHANYUE = 322,
    SPINNING_MDA = 323,
    HILLDATING = 324,
    AERO_SENSOR = 325,
    NIKE = 326,
    MAGICSHINE = 327,
    ICTRAINER = 328,
    ABSOLUTE_CYCLING = 329,
    EO_SWIMBETTER = 330,
    MYWHOOSH = 331,
    RAVEMEN = 332,
    TEKTRO_RACING_PRODUCTS = 333,
    DARAD_INNOVATION_CORPORATION = 334,
    CYCLOPTIM = 335,
    RUNNA = 337,
    ACTIGRAPHCORP = 5759,
}

/**
 * Concept2 product IDs
 */
export enum Concept2Product {
    PM5 = 20,
    PM4 = 8,
    PM3 = 4,
}

/**
 * Source type enum
 * Indicates where the data originated
 */
export enum FitSourceType {
    ANT = 0,
    ANT_PLUS = 1,
    BLUETOOTH = 2,
    BLUETOOTH_LOW_ENERGY = 3,
    WIFI = 4,
    LOCAL = 5,
}

/**
 * Sport type enum
 */
export enum FitSport {
    GENERIC = 0,
    RUNNING = 1,
    CYCLING = 2,
    TRANSITION = 3, // Mulitsport transition
    FITNESS_EQUIPMENT = 4,
    SWIMMING = 5,
    BASKETBALL = 6,
    SOCCER = 7,
    TENNIS = 8,
    AMERICAN_FOOTBALL = 9,
    TRAINING = 10,
    WALKING = 11,
    CROSS_COUNTRY_SKIING = 12,
    ALPINE_SKIING = 13,
    SNOWBOARDING = 14,
    ROWING = 15,
    MOUNTAINEERING = 16,
    HIKING = 17,
    MULTISPORT = 18,
    PADDLING = 19,
    FLYING = 20,
    E_BIKING = 21,
    MOTORCYCLING = 22,
    BOATING = 23,
    DRIVING = 24,
    GOLF = 25,
    HANG_GLIDING = 26,
    HORSEBACK_RIDING = 27,
    HUNTING = 28,
    FISHING = 29,
    INLINE_SKATING = 30,
    ROCK_CLIMBING = 31,
    SAILING = 32,
    ICE_SKATING = 33,
    SKY_DIVING = 34,
    SNOWSHOEING = 35,
    SNOWMOBILING = 36,
    STAND_UP_PADDLEBOARDING = 37,
    SURFING = 38,
    WAKEBOARDING = 39,
    WATER_SKIING = 40,
    KAYAKING = 41,
    RAFTING = 42,
    WINDSURFING = 43,
    KITESURFING = 44,
    TACTICAL = 45,
    JUMPMASTER = 46,
    BOXING = 47,
    FLOOR_CLIMBING = 48,
    BASEBALL = 49,
    DIVING = 53,
    HIIT = 62,
    RACKET = 64,
    WHEELCHAIR_PUSH_WALK = 65,
    WHEELCHAIR_PUSH_RUN = 66,
    MEDITATION = 67,
    DISC_GOLF = 69,
    CRICKET = 71,
    RUGBY = 72,
    HOCKEY = 73,
    LACROSSE = 74,
    VOLLEYBALL = 75,
    WATER_TUBING = 76,
    WAKESURFING = 77,
    MIXED_MARTIAL_ARTS = 80,
    SNORKELING = 82,
    DANCE = 83,
    JUMP_ROPE = 84,
    ALL = 254, // All is for goals only to include all sports.
}

/**
 * Sub-sport type enum
 */
export enum FitSubSport {
    GENERIC = 0,
    TREADMILL = 1,
    STREET = 2,
    TRAIL = 3,
    TRACK = 4,
    SPIN = 5,
    INDOOR_CYCLING = 6,
    ROAD = 7,
    MOUNTAIN = 8,
    DOWNHILL = 9,
    RECUMBENT = 10,
    CYCLOCROSS = 11,
    HAND_CYCLING = 12,
    TRACK_CYCLING = 13,
    INDOOR_ROWING = 14,
    ELLIPTICAL = 15,
    STAIR_CLIMBING = 16,
    LAP_SWIMMING = 17,
    OPEN_WATER = 18,
}

/**
 * Event type enum
 */
export enum FitEventType {
    START = 0,
    STOP = 1,
    CONSECUTIVE_DEPRECIATED = 2,
    MARKER = 3,
    STOP_ALL = 4,
    BEGIN_DEPRECIATED = 5,
    END_DEPRECIATED = 6,
    END_ALL_DEPRECIATED = 7,
    STOP_DISABLE = 8,
    STOP_DISABLE_ALL = 9,
}

/**
 * Event enum
 */
export enum FitEvent {
    TIMER = 0,
    WORKOUT = 3,
    WORKOUT_STEP = 4,
    POWER_DOWN = 5,
    POWER_UP = 6,
    OFF_COURSE = 7,
    SESSION = 8,
    LAP = 9,
    COURSE_POINT = 10,
    BATTERY = 11,
    VIRTUAL_PARTNER_PACE = 12,
    HR_HIGH_ALERT = 13,
    HR_LOW_ALERT = 14,
    SPEED_HIGH_ALERT = 15,
    SPEED_LOW_ALERT = 16,
    CAD_HIGH_ALERT = 17,
    CAD_LOW_ALERT = 18,
    POWER_HIGH_ALERT = 19,
    POWER_LOW_ALERT = 20,
    RECOVERY_HR = 21,
    BATTERY_LOW = 22,
    TIME_DURATION_ALERT = 23,
    DISTANCE_DURATION_ALERT = 24,
    CALORIE_DURATION_ALERT = 25,
    ACTIVITY = 26,
    FITNESS_EQUIPMENT = 27,
}

/**
 * Lap trigger enum
 */
export enum FitLapTrigger {
    MANUAL = 0,
    TIME = 1,
    DISTANCE = 2,
    POSITION_START = 3,
    POSITION_LAP = 4,
    POSITION_WAYPOINT = 5,
    POSITION_MARKED = 6,
    SESSION_END = 7,
    FITNESS_EQUIPMENT = 8,
}

/**
 * Activity type enum
 */
export enum FitActivityType {
    MANUAL = 0,
    AUTO_MULTI_SPORT = 1,
}
